GET http://localhost:8000/device

###

GET http://localhost:8000/device/39346161323164642d383762

###

POST http://localhost:8000/device
Content-Type: application/json

{
    "name": "土田のデバイス500",
    "model": "CC2L",
    "description": "古い"
}

###
POST http://localhost:8000/device/auto-data
Content-Type: application/json

{
    "dataSize": 30
}

###

PATCH  http://localhost:8000/device
Content-Type: application/json

{
    "id": "32396636626336372d363736",
    "name": "土田のデバイス500",
    "model": "CC2L",
    "description": "古い"
}

###
DELETE  http://localhost:8000/device
Content-Type: application/json

{
    "deviceIds": ["65a5522b6b401bc743abf311"]
}
###
