
GET http://localhost:8000/app/device

###
GET http://localhost:8000/app/device?name=4


###

GET http://localhost:8000/app/device/39346161323164642d383762

###

POST http://localhost:8000/app/device
Content-Type: application/json

{
    "name": "tsuchida80d0",
    "model": "CC2L",
    "description": "新しい"
}

###

POST http://localhost:8000/app/user
Content-Type: application/json

{
    "name": "tsuchida",
    "mailAddress": "tsuchishinka@gmail.com",
    "password": "j68VmsBW"
}

###

GET http://localhost:8000/app/user
###

GET http://localhost:8000/app/user?name=chi
###

GET http://localhost:8000/app/user/31373736323062382d383831


###

POST http://localhost:8000/app/
Content-Type: application/json

{
    "mailAddress": "tsuchishinka@gmail.com",
    "password": "j68VmsBW"
}

###
POST http://localhost:8000/app/device/auto-data
Content-Type: application/json

{
    "dataSize": 30
}

###

PATCH  http://localhost:8000/app/device
Content-Type: application/json

{
    "id": "39346161323164642d383762",
    "name": "tsuchida700",
    "model": "CC2L",
    "description": "古い"
}

###
DELETE  http://localhost:8000/app/device
Content-Type: application/json

{
    "deviceIds": ["65a5522b6b401bc743abf311"]
}
###
