
GET http://localhost:8000/app/device

###
GET http://localhost:8000/app/device?name=4


###

GET http://localhost:8000/app/device/39346161323164642d383762

###

POST http://localhost:8000/app/device
Content-Type: application/json

{
    "name": "tsuchida80d0",
    "model": "CC2L",
    "description": "新しい"
}

###

POST https://basic-web-app-z1i9.onrender.com/app/device
Content-Type: application/json

{
    "name": "devic2323e2332",
    "model": "CC23323223L2",
    "description": "新しい"
}

###

POST http://localhost:8000/app/user
Content-Type: application/json

{
    "name": "tsuchida",
    "mail_address": "tsuchishinka@gmail.com",
    "password": "j68VmsBW"
}

###

POST https://basic-web-app-z1i9.onrender.com/app/user
Content-Type: application/json

{
    "name": "test",
    "mail_address": "test@example.com",
    "password": "password"
}

###

GET http://localhost:8000/app/user
###

GET http://localhost:8000/app/user?name=chi
###

GET http://localhost:8000/app/user/31373736323062382d383831


###

POST http://localhost:8000/app/
Content-Type: application/json

{
    "mail_address": "tsuchishinka@gmail.com",
    "password": "j68VmsBW"
}

###

POST http://localhost/app/
Content-Type: application/json

{
    "mail_address": "tsuchishinka@gmail.com",
    "password": "j68VmsBW"
}
###

POST https://basic-web-app-z1i9.onrender.com/app/
Content-Type: application/json

{
    "mail_address": "tsuchishinka@gmail.com",
    "password": "j68VmsBW"
}

###
POST http://localhost:8000/app/device/auto-data
Content-Type: application/json

{
    "dataSize": 30
}

###

PATCH  http://localhost:8000/app/device
Content-Type: application/json

{
    "id": "39346161323164642d383762",
    "name": "tsuchida700",
    "model": "CC2L",
    "description": "古い"
}

###
DELETE  http://localhost:8000/app/device
Content-Type: application/json

{
    "device_ids": ["65a5522b6b401bc743abf311"]
}
###
