const USER_NAME_MAX_LENGTH = 32

const MAIL_ADDRESS_REGIX = /^[A-Za-z0-9]+@[A-Za-z0-9]+\.[A-Za-z0-9]+/

const MAIL_ADDRESS_MAX_LENGTH = 64

export { MAIL_ADDRESS_MAX_LENGTH, MAIL_ADDRESS_REGIX, USER_NAME_MAX_LENGTH }
