const TYPE_TEMPLATE = `type {$NAME} = {$TYPE}`;

const ARG_DESCRIPTION_TEMPLATE = `* @param {$NAME} {$DESCRIPTION}`;

const DESCRIPTION_TEMPLATE = `/**
 * {$DESCRIPTION}
 {$ARG_DESCRIPTION} 
 */`;

const ARG_TEMPLATE = `{$NAME}: {$TYPE}`;

const FUNCTION_TEMPLATE = `
{$TYPE}

{$DESCRIPTION}
const {$NAME} = ({$ARGS}){$RETURN_TYPE} => {
  /** コードを記述 **/
}

export { {$NAME} }
`;

export {
  ARG_DESCRIPTION_TEMPLATE,
  ARG_TEMPLATE,
  DESCRIPTION_TEMPLATE,
  FUNCTION_TEMPLATE,
  TYPE_TEMPLATE,
};
